### ISSUE TITLE
Is chef_version necessary in metadata.rb?

### ISSUE THREAD

**Issue by thomasdziedzic** [bahchis/airflow-cookbook#13]
We are currently running an older version of chef

```
sudo env -i chef-client --version
Chef: 12.14.89
```

I just encountered the version bound specified in the metadata.rb file `chef_version     '~>12.19'` which prevents me from using this cookbook because the converge fails.

Is the chef_version necessary?
https://github.com/bahchis/airflow-cookbook/commit/915230ad2147c649e2249136c0633059325e5b10

Thank you for your time!

**Comment by bahchis** [comment]
Good point @thomasdziedzic, actually I think it was a bad call on my side to put it there in the first place.
The reason it is there: https://github.com/chef/chef/issues/5836
Still, the current chef_version does not solve it. From what I checked, the chef_version should be:
12.1.0 - 12.19.25 and 12.20.3+

So your current version should be working fine.
Mind changing it and submitting a PR? I will gladly accept.
