### ISSUE TITLE
Noobie Question

### ISSUE THREAD

**Issue by pedrorjbr** [bahchis/airflow-cookbook#6]
I am trying to use Airflow Cookbook on OpsWorks. 
Looking at the folder var/chef/runs/xxxx I see:

/var/chef/runs/e8180f46-7954-47d4-8323-dfac8fcbe471
```
{
  "airflow": {
    "config": {
      "core": {
        "sql_alchemy_conn": "postgresql://DEVOPS:tYDp72c4@devops.cdgimnnbnjqc.us-west-2.rds.amazonaws.com:5432/airflow",
        "parallelism": 10,
        "executor": "LocalExecutor"
      }
    }
  },
  "run_list": [
    "recipe[airflow::webserver]",
    "recipe[airflow::scheduler]"
  ]
}
```

I see that the airflow.cfg is been generated on folder /usr/local/lib/airflow. So when I start Airflow it not uses this file, it uses the ~/airflow/airflow.cfg.

Does anyone can help me?

**Comment by bahchis** [comment]
Hi @pedrorjbr,
Are you on Ubuntu or CentOS? Do you start Airflow with the services generated by the cookbook or manually in the shell?

Thanks

**Comment by bahchis** [comment]
Hi @pedrorjbr 
The thing that comes to mind is that the environment variable AIRFLOW_HOME has not taken effect. I will need more details to try and resolve it.

I am closing this issue for now.

**Comment by ellen-liu** [comment]
I'm running the services generated by the cookbook, but I realized that they are not working because 'airflow initdb' initializes the database in the home directory (default) and not the directory specified by the cookbook configuration file. Am I supposed to run the initdb command differently?

**Comment by ellen-liu** [comment]
hello- this is a follow up!
I am using the cookbook on Ubuntu and have set the environment variable to the AIRFLOW_HOME setting in the right environment file (in etc/default). However, when I run `airflow initdb`, I notice that the database is being initialized in my ~/ home directory, which is not the correct place and is the default home for Airflow itself, not what the cookbook specifies. Then, when I run the services from the cookbook, the webserver tries to access a database that does not exist.

**Comment by bahchis** [comment]
Hi Ellen,
The cookbook generates the environment file which gets loaded by the init system.
The `airflow initdb` command is executed in the shell that does not export the variable in that file automatically.

What you should do is export the AIRFLOW_HOME variable before running the initdb command:
```
export AIRFLOW_HOME=<the directory as it appears in the service environment file>
airflow initdb
```

Please try and let me know if this solves your issue.

**Comment by ellen-liu** [comment]
I exported the AIRFLOW_HOME variable - this time the `airflow initdb `command tried to execute in the correct directory (in the service environment file), however a readonly error comes up. When I run with higher permissions, `airflow initdb` reverts back to initializing the database in the wrong, default directory for Airflow.

**Comment by bahchis** [comment]
Sorry @ellen-liu I forgot to mention that the commands should be executed using the `airflow` user. I have edited my previous comment so all commands will be in one place.
